[Windows] SetID
Countly/countly-sdk-windows pull request #135
Opened 2024-06-10 10:44 UTC by arifBurakDemiray

2024-06-10 12:39 UTC, AliRKat approved these changes
LGTM 🚀

2024-06-12 10:46 UTC, turtledreams requested changes
neat! we do have tests for windows rite?

2024-06-12 13:08 UTC, arifBurakDemiray commented
> neat! we do have tests for windows rite?

Yes we have, I forgot, I will add those @turtledreams

2024-07-08 09:41 UTC, AliRKat approved these changes

2024-11-05 10:31 UTC, AliRKat approved these changes

2024-11-06 08:16 UTC, turtledreams requested changes

2024-11-06 08:16 UTC, turtledreams commented on countlyCommon/countlyCommon/CountlyBase.cs
> +        {
need logs

2024-11-06 14:33 UTC, turtledreams approved these changes

2024-11-06 14:34 UTC, merged