[Sdk 514] Consent removed on changind device id without merge
Countly/countly-sdk-windows pull request #36
Opened 2021-12-03 07:15 UTC by ZahidZafar

2021-12-06 13:57 UTC, ArtursKadikis requested changes
Add 2 meaninigful tests to validate this functionality

2021-12-06 13:57 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/CountlyBase.cs
> +        internal enum ConsentChangedAction
Move this declaration (together with the decleration of the "ConsentFeatures" enum, "consentRequired ", "givenConsent ") to the top

2021-12-06 13:57 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/CountlyBase.cs
> -            UtilityHelper.CountlyLogging("[CountlyBase] Calling 'SetConsent'");
It's an error to remove this log call as that removes an important piece of information in the calling chain logs

2021-12-06 13:57 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/CountlyBase.cs
> +                    Dictionary<ConsentFeatures, bool> removedConsent = new Dictionary<ConsentFeatures, bool>();
Rework this into an internal call to remove all consent.

2022-01-05 08:40 UTC, ArtursKadikis commented
@ZahidZafar this has a merge conflict

2022-02-25 12:58 UTC, ArtursKadikis requested changes
Rename "RemoveAllConsent" to "RemoveAllConsentInternal".

Add 2 meaningful tests to this change.

2022-03-09 22:55 UTC, ArtursKadikis requested changes
Major breaking changes should be at the top in the changelog.

None of the added tests are validating the changes in this PR.

2022-04-05 08:55 UTC, ZahidZafar commented
> Major breaking changes should be at the top in the changelog.
> 
> None of the added tests are validating the changes in this PR.
**
![image](https://user-images.githubusercontent.com/8924406/161716970-1aaa9188-d456-4842-a83f-f8f3b0d78220.png)
**
I have posted an image in which consents are being validated on changing device id without merge.
Please let me know what kind of unit test you have in mind.

2022-04-20 08:01 UTC, ArtursKadikis requested changes

2022-04-20 08:01 UTC, ArtursKadikis commented on countlyCommon/TestingRelated/DeviceIdTests.cs
> +            }
give consent afterwards and the verify

2022-04-25 17:56 UTC, ArtursKadikis approved these changes

2022-04-25 17:56 UTC, merged