[SDK 328] Unique time stamp
Countly/countly-sdk-windows pull request #39
Opened 2021-12-29 08:01 UTC by ZahidZafar

2022-01-04 16:03 UTC, ArtursKadikis requested changes
This PR adds "state" in a static variable, that should not be done. Rework this PR (and probably the TimeHelper class) so that nothing is stored in a static variable.

2022-01-05 07:56 UTC, ZahidZafar commented
> This PR adds "state" in a static variable, that should not be done. Rework this PR (and probably the TimeHelper class) so that nothing is stored in a static variable.

To remove static variables and functions that are being used in the whole SDK I have to create a single instance of 'Timehelper' class pass to all classes to use this one.

2022-01-17 19:10 UTC, ArtursKadikis requested changes
"ToUnixTime" should be reverted back to it's original logic. You are changing it's purpose. It should only create a unix timestamp out of a DateTime. 
Move the new "unique time" logic to "UnixTimeNow".
"UnixTimeNow" should be renamed to "GetUniqueUnixTime".

2022-02-16 12:51 UTC, ZahidZafar commented on countlyCommon/TestingRelated/RequestTestCases.cs
> -            Assert.True(req2.EndsWith("&sdk_version=c&sdk_name=d"));
This test has been updated in another ticket, but I am updating it back here on your request.

2022-02-22 18:26 UTC, ArtursKadikis requested changes
You are again ignoring the required changed. There is no "GetUniqueInstant" call in the "TimeHelper" class. That is the function that should be used.
By ignoring that class you are again introducing another bug by not guaranteing unique timestamps.

Change the timezone data type to "String"

2022-02-22 18:26 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/Helpers/TimeHelper.cs
> +            internal TimeInstant()
This constructor should not exist

2022-02-22 18:26 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/Helpers/TimeHelper.cs
> +            internal TimeInstant(long timestampInMillis, int hour, int dow)
This constructor needs all 4 fields. The timezone is not set bellow and you are already introducing a bug.

2022-02-22 18:26 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/Helpers/TimeHelper.cs
> +            internal static TimeInstant Get(long timestampInMillis)
This doesn't set a timezone

2022-02-22 18:27 UTC, ArtursKadikis requested changes

2022-02-22 18:27 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/Helpers/TimeHelper.cs
> +            long calculatedMillis =  ToUnixTime(DateTime.Now.ToUniversalTime());
reduntant empty space

2022-02-25 12:42 UTC, merged