[Sdk 366] SDK Internal Limits and unit tests added
Countly/countly-sdk-windows pull request #41
Opened 2021-12-30 10:29 UTC by ZahidZafar

2022-01-04 16:44 UTC, ArtursKadikis requested changes
These test files should also be added to flavours other than 3.5 and 4.0.

Move the trimming calls to a utility function.

2022-01-04 16:44 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/Entities/EntityBase/CountlyUserDetailsBase.cs
> +        internal bool isNotificationEnabled { get; set; }
Add the "ignore" tag to this.

2022-02-16 12:55 UTC, ZahidZafar commented
> These test files should also be added to flavours other than 3.5 and 4.0.
> 
> Move the trimming calls to a utility function.
trim calls need configuration object, configuration object is part of 'Countly' instance. So to move these call in utility functions I will have to pass configuration object as well.
we have discussed it before as well.

2022-02-18 01:31 UTC, ArtursKadikis commented
The trimming calls are still not moved to a utility class.

2022-02-18 09:17 UTC, ZahidZafar commented
I left a comment, please read and left resonse.

2022-02-22 18:39 UTC, ArtursKadikis requested changes
"UserDetailTests .cs" has not only a whitespace in it it's name, but the name is also missing a letter. It should be "UserDetailsTests"

No code formatting has been performed on these changes.

Throughout these changes you have added a lot of double empty lines. Replace them with a single empty line.

2022-02-22 18:39 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/CountlyBase.cs
> +        private string ManipulateStackTrace(string stackTrace)
This has not been moved to the utility class.

2022-02-22 18:39 UTC, ArtursKadikis commented on countlyCommon/countlyCommon/CountlyBase.cs
> +            ;
This is a useless semicolon

2022-02-25 12:51 UTC, ArtursKadikis requested changes
Key trimming should be moved to a common place

2022-02-28 09:03 UTC, ZahidZafar commented
> Key trimming should be moved to a common place

We can move 'Key trimming' logic into 'RecordInternEvent' method or into a new method.
One more thing if user set the 'MaxKeyLenght' less than predefine internal event keys e.g '[CLY]_star_rating', then it will get trim and internal events  feature will not work accordingly. (edited)

2022-02-28 12:36 UTC, merged